### ISSUE TITLE
add ability to backup selectable or all dialogs with 1 click

### ISSUE THREAD

**Issue by johnstrong1** [LonamiWebs/Telebackup#6]
hi
first things first !
your projects ( telethon and telebackup ) are awesome

and it will be nice if we could download whole history with 1 click (include or exclude channels or supergroups)

i`ll be gratefull

and create some online donation page ...

**Comment by Lonami** [comment]
I need to work more on it though. Currently you cannot switch from one backup to the previous or next one, it's automatic.

**Comment by Lonami** [comment]
This little work on [`fb1801a`](https://github.com/LonamiWebs/Telebackup/commit/fb1801aba1d574bdc9c42c0d652af5f45573bfa5) should be enough. Please let me know what you think.

**Comment by johnstrong1** [comment]
hi dear
i think i could not make my point
i meant backup whole dialogs in one click ! (only chats and groups not channels)

**Comment by Lonami** [comment]
> i meant backup whole dialogs in one click

Well… now you can select only those you want which is kind of better. And you can still select all those you want, so I don't think I'll be changing it more (feel free to make a pull request). It's faster than clicking one, stopping, going back, loading dialogs… and then again, starting over.

**Comment by Lonami** [comment]
Wrong button.
