### ISSUE TITLE
An issue in select_dialog_window.py

### ISSUE THREAD

**Issue by parazitt** [LonamiWebs/Telebackup#7]
I found an issue in [this function](https://github.com/LonamiWebs/Telebackup/blob/master/gui/windows/select_dialog_window.py#L88-L111).
the function uses offset_date for load more dialogs and it way is not secure, i suggest using offset_id for more better and reliable result.
tank you

**Comment by Lonami** [comment]
> i suggest using offset_id for more better and reliable result

I tried, but I didn't manage to work with it :) — if you know how to properly use the `offset_id` parameter feel free to open a pull request.

**Comment by Lonami** [comment]
Reopen with better arguments if you want to me to change it :P, closing for now, since it works as is.
