### ISSUE TITLE
_tkinter.TclError: couldn't recognize data in image file "gui/res/png/backspace.png"

### ISSUE THREAD

**Issue by sillasgonzaga** [LonamiWebs/Telebackup#8]
WHat can possibly be the cause of this error?

**Comment by Lonami** [comment]
It renders fine [on my browser](https://github.com/LonamiWebs/Telebackup/blob/master/gui/res/png/backspace.png) and when downloading the file, and so does when I download it, and the file seems to be indeed a `.png`… I will try reencoding the image with `ffmpeg` later.

**Comment by Lonami** [comment]
Give it a go and let me know how it went, again, it works fine for me.

**Comment by Lonami** [comment]
Reopen if the issue still happens after you've tested. For now I will consider it as working.
