### ISSUE TITLE
ChannelForbiden object has no attribute Date

### ISSUE THREAD

**Issue by johnstrong1** [LonamiWebs/Telebackup#9]
hi dear
1) i have this problem 

![image](https://user-images.githubusercontent.com/12671628/27176607-775c9e8e-51d8-11e7-9d1d-c1bdb20521f7.png)

2) it would be good if we could backup 2 profile at same time
and profiles had different folders in output

**Comment by Lonami** [comment]
> it would be good if we could backup 2 profile at same time

You can.

> and profiles had different folders in output

They do.

**Comment by johnstrong1** [comment]
i mean backup two numbers at same time
user_phone1=+123456789
session_name1=user1

userphone2=+987654321
session_name2=user2

**Comment by Lonami** [comment]
Maybe you could try running a second instance on a different folder. Also note that Telebackup is actually a bit breaky. I'd like to rewrite it better.
